//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TowerWarfare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TowerWarfare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] box {
            get {
                object obj = ResourceManager.GetObject("box", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] box1 {
            get {
                object obj = ResourceManager.GetObject("box1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bricks {
            get {
                object obj = ResourceManager.GetObject("bricks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] buddha {
            get {
                object obj = ResourceManager.GetObject("buddha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] buddha1 {
            get {
                object obj = ResourceManager.GetObject("buddha1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bunny {
            get {
                object obj = ResourceManager.GetObject("bunny", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bunny1 {
            get {
                object obj = ResourceManager.GetObject("bunny1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using StarchUICore;
        ///using UmamiScriptingCore.Behaviors;
        ///using UmamiScriptingCore.Behaviors.Nodes.Leaves;
        ///
        ///namespace TowerWarfare.Resources.Behaviors.Nodes
        ///{
        ///    public class ButtonPushNode : LeafNode
        ///    {
        ///        protected override void Execute(BehaviorContext context)
        ///        {
        ///            if (context.GetComponent&lt;IElement&gt;() is Element element)
        ///            {
        ///                //element.Position = element.Position.Offset(Unit.Pixels(element.Location.X + 10), Unit.Pixels(element.Location.Y + 10)) [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ButtonPushNode {
            get {
                return ResourceManager.GetString("ButtonPushNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Camera {
            get {
                object obj = ResourceManager.GetObject("Camera", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using SpiceEngine.GLFWBindings.Inputs;
        ///using SpiceEngineCore.Entities.Cameras;
        ///using SpiceEngineCore.Geometry;
        ///using SpiceEngineCore.Utilities;
        ///using System;
        ///using TangyHIDCore;
        ///using UmamiScriptingCore;
        ///using UmamiScriptingCore.Behaviors;
        ///using UmamiScriptingCore.Behaviors.Nodes;
        ///
        ///namespace TowerWarfare.Resources.Behaviors.Nodes
        ///{
        ///    public class CameraNode : Node
        ///    {
        ///        public const float STRAFE_SCALE = 0.002f;
        ///        public const float TRAVEL_SCALE = 0.02f;
        ///        public const f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CameraNode {
            get {
                return ResourceManager.GetString("CameraNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap diffuse {
            get {
                object obj = ResourceManager.GetObject("diffuse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dragon {
            get {
                object obj = ResourceManager.GetObject("dragon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dragon1 {
            get {
                object obj = ResourceManager.GetObject("dragon1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap drkwood2 {
            get {
                object obj = ResourceManager.GetObject("drkwood2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EnemyPatrol {
            get {
                object obj = ResourceManager.GetObject("EnemyPatrol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap engineflare1 {
            get {
                object obj = ResourceManager.GetObject("engineflare1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fireworks_red {
            get {
                object obj = ResourceManager.GetObject("fireworks_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap guard1_body {
            get {
                object obj = ResourceManager.GetObject("guard1_body", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap guard1_face {
            get {
                object obj = ResourceManager.GetObject("guard1_face", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap guard1_helmet {
            get {
                object obj = ResourceManager.GetObject("guard1_helmet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap heightmap {
            get {
                object obj = ResourceManager.GetObject("heightmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hheli {
            get {
                object obj = ResourceManager.GetObject("hheli", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] hheli1 {
            get {
                object obj = ResourceManager.GetObject("hheli1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] hheli2 {
            get {
                object obj = ResourceManager.GetObject("hheli2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iron_grill {
            get {
                object obj = ResourceManager.GetObject("iron_grill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] jeep {
            get {
                object obj = ResourceManager.GetObject("jeep", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap jeep_army {
            get {
                object obj = ResourceManager.GetObject("jeep_army", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap jeep_rood {
            get {
                object obj = ResourceManager.GetObject("jeep_rood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] jeep1 {
            get {
                object obj = ResourceManager.GetObject("jeep1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] monkey {
            get {
                object obj = ResourceManager.GetObject("monkey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] monkey1 {
            get {
                object obj = ResourceManager.GetObject("monkey1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap monster_hellknight {
            get {
                object obj = ResourceManager.GetObject("monster_hellknight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap monster_hellknight1 {
            get {
                object obj = ResourceManager.GetObject("monster_hellknight1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Newtonsoft.Json;
        ///using SavoryPhysicsCore;
        ///using SavoryPhysicsCore.Bodies;
        ///using UmamiScriptingCore;
        ///using UmamiScriptingCore.Behaviors;
        ///using UmamiScriptingCore.Behaviors.Nodes;
        ///
        ///using Color4 = SpiceEngineCore.Geometry.Color4;
        ///using Matrix2 = SpiceEngineCore.Geometry.Matrix2;
        ///using Matrix3 = SpiceEngineCore.Geometry.Matrix3;
        ///using Matrix4 = SpiceEngineCore.Geometry.Matrix4;
        ///using Quaternion = SpiceEngineCore.Geometry.Quaternion;
        ///using Vector2 = SpiceEngineCore.Geometry.Vector2;
        ///using Vect [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MoveToNode {
            get {
                return ResourceManager.GetString("MoveToNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap normal_map {
            get {
                object obj = ResourceManager.GetObject("normal_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap normal_up {
            get {
                object obj = ResourceManager.GetObject("normal_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using SpiceEngine.GLFWBindings.Inputs;
        ///using SpiceEngineCore.Entities.Cameras;
        ///using SpiceEngineCore.Utilities;
        ///using System;
        ///using TangyHIDCore;
        ///using UmamiScriptingCore;
        ///using UmamiScriptingCore.Behaviors;
        ///using UmamiScriptingCore.Behaviors.Nodes;
        ///using Vector2 = SpiceEngineCore.Geometry.Vector2;
        ///using Vector3 = SpiceEngineCore.Geometry.Vector3;
        ///
        ///namespace TowerWarfare.Resources.Behaviors.Nodes
        ///{
        ///    public class PerspectiveCameraNode : Node
        ///    {
        ///        public const float MIN_DISTANCE = 1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PerspectiveCameraNode {
            get {
                return ResourceManager.GetString("PerspectiveCameraNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] phoenix_ugv {
            get {
                object obj = ResourceManager.GetObject("phoenix_ugv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] quad {
            get {
                object obj = ResourceManager.GetObject("quad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] quad_r {
            get {
                object obj = ResourceManager.GetObject("quad_r", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] quad1 {
            get {
                object obj = ResourceManager.GetObject("quad1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] quad2 {
            get {
                object obj = ResourceManager.GetObject("quad2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] quad21 {
            get {
                object obj = ResourceManager.GetObject("quad21", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_grill {
            get {
                object obj = ResourceManager.GetObject("round_grill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sp3back {
            get {
                object obj = ResourceManager.GetObject("sp3back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sp3bot {
            get {
                object obj = ResourceManager.GetObject("sp3bot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sp3front {
            get {
                object obj = ResourceManager.GetObject("sp3front", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sp3left {
            get {
                object obj = ResourceManager.GetObject("sp3left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sp3right {
            get {
                object obj = ResourceManager.GetObject("sp3right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sp3top {
            get {
                object obj = ResourceManager.GetObject("sp3top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sphere {
            get {
                object obj = ResourceManager.GetObject("sphere", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sphere1 {
            get {
                object obj = ResourceManager.GetObject("sphere1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spider {
            get {
                object obj = ResourceManager.GetObject("spider", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spider1 {
            get {
                object obj = ResourceManager.GetObject("spider1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SpiderTex {
            get {
                object obj = ResourceManager.GetObject("SpiderTex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap test {
            get {
                object obj = ResourceManager.GetObject("test", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Cameras&quot;:[{&quot;Name&quot;:&quot;MainCamera&quot;,&quot;AttachedEntityName&quot;:null,&quot;Type&quot;:1,&quot;ZNear&quot;:0.1,&quot;ZFar&quot;:1000.0,&quot;StartingWidth&quot;:0.0,&quot;FieldOfViewY&quot;:0.7853982,&quot;Behavior&quot;:{&quot;Name&quot;:null,&quot;FilePath&quot;:null,&quot;RootNode&quot;:{&quot;Arguments&quot;:[],&quot;NodeType&quot;:4,&quot;Children&quot;:[{&quot;Arguments&quot;:[{&quot;Value&quot;:0.02,&quot;Type&quot;:&quot;System.Single, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;},{&quot;Value&quot;:0.001,&quot;Type&quot;:&quot;System.Single, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;},{&quot;Value&quot;:1.0,&quot;Type&quot;:&quot;System.Single,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TestMap {
            get {
                return ResourceManager.GetString("TestMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using SavoryPhysicsCore;
        ///using SavoryPhysicsCore.Bodies;
        ///using SpiceEngineCore.Entities.Actors;
        ///using SpiceEngineCore.Utilities;
        ///using System;
        ///using UmamiScriptingCore;
        ///using UmamiScriptingCore.Behaviors;
        ///using UmamiScriptingCore.Behaviors.Nodes;
        ///
        ///using Color4 = SpiceEngineCore.Geometry.Color4;
        ///using Matrix2 = SpiceEngineCore.Geometry.Matrix2;
        ///using Matrix3 = SpiceEngineCore.Geometry.Matrix3;
        ///using Matrix4 = SpiceEngineCore.Geometry.Matrix4;
        ///using Quaternion = SpiceEngineCore.Geometry.Quaternio [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TurnTowardsNode {
            get {
                return ResourceManager.GetString("TurnTowardsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wal67ar_small {
            get {
                object obj = ResourceManager.GetObject("wal67ar_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wal69ar_small {
            get {
                object obj = ResourceManager.GetObject("wal69ar_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap white {
            get {
                object obj = ResourceManager.GetObject("white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
